### ISSUE TITLE
rehlds crash, segmentation fault $HL_CMD

### ISSUE THREAD

**Issue by infamanious** [Theggv/Kreedz#28]
I compiled all the plugins manually instead of using amxxpack and they all compiled flawlessly. Also compiled amxxhttp, reapi, rehlds,regamedl myself. I downloaded amxarch from binary. 

The error occurs with kz_sql_core.amxx enabled, but doesn't crash when its disabled.

Despite compiling correctly these plugins also dont run settings_mysql,kz_sql_savepos, kz_sql_top because their missing a module according to the debug output.

I've also tried using amxxpack with the same problems

`ReGameDLL version: 5.21.0.0-dev
Metamod-r v1.3.0.131, API (5:13)
ReHLDS version: 3.12.0.0-dev
 [ 1] AMX Mod X       RUN   -    amxmodx_mm_i386.so        v1.9.0.5294    ini  Start ANY  
 [ 2] MySQL           RUN   -    mysql_amxx_i386.so        v1.9.0.5294    pl1  ANY   ANY  
 [ 3] SQLite          RUN   -    sqlite_amxx_i386.so       v1.9.0.5294    pl1  ANY   ANY  
 [ 4] Fun             RUN   -    fun_amxx_i386.so          v1.9.0.5294    pl1  ANY   ANY  
 [ 5] Engine          RUN   -    engine_amxx_i386.so       v1.9.0.5294    pl1  ANY   ANY  
 [ 6] FakeMeta        RUN   -    fakemeta_amxx_i386.so     v1.9.0.5294    pl1  ANY   ANY  
 [ 7] GeoIP           RUN   -    geoip_amxx_i386.so        v1.9.0.5294    pl1  ANY   ANY  
 [ 8] CStrike         RUN   -    cstrike_amxx_i386.so      v1.9.0.5294    pl1  ANY   ANY  
 [ 9] CSX             RUN   -    csx_amxx_i386.so          v1.9.0.5294    pl1  ANY   ANY  
 [10] Ham Sandwich    RUN   -    hamsandwich_amxx_i386.so  v1.9.0.5294    pl1  ANY   ANY  
 [11] ReAPI           RUN   -    reapi_amxx_i386.so        v5.22.0.0-dev  pl1  ANY   Never
 [12] Amxx Easy Http  RUN   -    easyhttp_amxx_i386.so     v1.1.1         pl1  ANY   ANY  
 [13] Amxx Archive    RUN   -    amxxarch_amxx_i386.so     v2.0           pl1  ANY   ANY  
[AMXX] Plugin "settings_mysql.amxx" failed to load: Plugin uses an unknown function (name "kz_sql_get_user_uid") - check your modules.ini.
[AMXX] Plugin "kz_sql_savepos.amxx" failed to load: Plugin uses an unknown function (name "kz_sql_get_map_uid") - check your modules.ini.
[AMXX] Plugin "kz_sql_top.amxx" failed to load: Plugin uses an unknown function (name "kz_sql_get_map_uid") - check your modules.ini.

./hlds_run: line 255: 18916 Segmentation fault      $HL_CMD
`

**Comment by Theggv** [comment]
Hi, did you configured connection data in `configs/kreedz.cfg`?

**Comment by infamanious** [comment]
After verifying, it appears that i did not configure the sql connection data properly.

**Comment by b0g1337** [comment]
> After verifying, it appears that i did not configure the sql connection data properly.

how did u configure it? im having trouble
