### ISSUE TITLE
when I join the spec, the server crashes.

### ISSUE THREAD

**Issue by vSxLc** [Theggv/Kreedz#29]
when I join the spec, the server crashes.
Oddly enough, when I use this fork https://github.com/Flummi/Kreedz it doesn't crash, but I don't like this fork and don't want to use it

**Comment by Flummi** [comment]
I think it was this fix: https://github.com/Theggv/Kreedz/commit/0d35b9b0e943d2b58bb2e6472f0dcceb69bdf09c

**Comment by vSxLc** [comment]
> I think it was this fix: [0d35b9b](https://github.com/Theggv/Kreedz/commit/0d35b9b0e943d2b58bb2e6472f0dcceb69bdf09c)

I replaced kz_remove_ents with your version and it no longer crashes!
I am really sorry to say that I don't like your version.

**Comment by Flummi** [comment]
it's okay, I thought the project was dead. so i forked it. :)
