### ISSUE TITLE
Savepos uses cp if you go for pro

### ISSUE THREAD

**Issue by muppet922** [Theggv/Kreedz#31]
Hi guys, thanks for this plugin, it is really great. I think there are some things that you can change if you want of course. 

So if you go for pro15 top, and game crashes and you come back savepos make 1cp and 1gc so no more pro15 place. Is it possible to change?

Also, how can I include in menu things like top, airaccelerate change? Thanks guys for your work and wish you a great day.

**Comment by Theggv** [comment]
Hi, I can't reproduce that savepos behaviour. I tested both release and master branches. Did that bug happen multiple times or only once?

**Comment by muppet922** [comment]
Interesting, when that happened my network connection failed... so when i tryed to reproduce the bug, it didn't happened and all worked how it should. I think the issue is not something present.

What about the features? Coloring when people make record for nob15,pro15. Including top15 in menu, maybe airaccelerate, sound when someone takes nr.1 place, of course if you want, afterall developing is a hassle and I am glad for this plugin anyways. 

Thanks again, sorry for bothering and wish you the best.
