### ISSUE TITLE
Please add /savestart

### ISSUE THREAD

**Issue by vSxLc** [Theggv/Kreedz#32]
Greatest plugin I've seen!
If this plugin had /savestart it would be perfect.
The /savestart saves the location and angle, and the /start teleports to that location and stops the timer.
It would be perfect if we could save that saved location in sql instead of temporarily.
I am new to gitbuh and didn't know where to post this.
Please forgive me for posting on issues.

**Comment by Flummi** [comment]
https://github.com/Flummi/Kreedz/commit/81dff387e450addadb399b802e685d5cdad5829a

Don't merge, it's only one of many modifications, it will break the main branch. Only for demonstration

**Comment by vSxLc** [comment]
> [Flummi@81dff38](https://github.com/Flummi/Kreedz/commit/81dff387e450addadb399b802e685d5cdad5829a)
> 
> Don't merge, it's only one of many modifications, it will break the main branch. Only for demonstration

Is this a plugin that saves start to spl?
Sorry for my lack of words.
What I am looking for is a plugin that saves the location and angle in /savestart like in kz rush server or prokreedz and teleports there in /start and stops the timer.

**Comment by Flummi** [comment]
it's only the foundation to save the startposition (if not already set) into SQL. No /savestart yet due lack of knowledge. :\
The angle is not taken into account because I didn't need it.

**Comment by Theggv** [comment]
WIP 966b2838a097cfbe981f0b6f716fefefbb41bf52.

**Comment by Theggv** [comment]
Implemented in #34.

**Comment by Flummi** [comment]
nice work :)
