### ISSUE TITLE
[error] [recordsTablehandler] [1054] Unknown colum 'last_name' in 'field list'

### ISSUE THREAD

**Issue by infamanious** [Theggv/Kreedz#33]
When displaying the top or nub records, this error outputs in the server console without any info displayed in game. Recreating the database didnt do anything. I also deleted the data/records cache and that didnt work as well. When i used the main branch this didnt happen, however i havent checked for any modifications since and now im using Flummis fork for the airaccelerate plugin. @Flummi

**Comment by infamanious** [comment]
so in the kz_sql_core there are a few lines that removed last_name , but in kz_sql top i found these on lines 96, 113, 168, 126
`SELECT `last_name`, `time`, `cp`, `tp` FROM `kz_uid` as user INNER JOIN \`

**Comment by Theggv** [comment]
Flummi uses different table structure.
https://github.com/Flummi/Kreedz/blob/a9bf1ac1a7f4c32a41fecfcace442126c07f34fd/src/scripts/kreedz/kz_sql_core.sma#L117

Change all `last_name` to `name` in queries in `kz_sql_top`.

**Comment by infamanious** [comment]
> Flummi uses different table structure. https://github.com/Flummi/Kreedz/blob/a9bf1ac1a7f4c32a41fecfcace442126c07f34fd/src/scripts/kreedz/kz_sql_core.sma#L117
> 
> Change all `last_name` to `name` in queries in `kz_sql_top`.

ahh that worked! nice! At first i tried just removing the entire line 'last_name' line.
