### ISSUE TITLE
Request: add prefix "nom" to nominate a map

### ISSUE THREAD

**Issue by francisSM** [Theggv/Kreedz#38]
Dear Theggv,

I hope this message finds you well. I wanted to take a moment to express my gratitude for your proyect and for keeping it up to date.

I was wondering if it would be possible for you to add a "nom" prefix to the map nomination process. For example, instead of simply typing "bhop_", the player would need to type "nom bhop_" in order to nominate a map.

Any assistance you can provide on this matter would be greatly appreciated. Thank you for your time and effort in maintaining this fantastic mod.

PD: By my side, I will continue trying to implement it, but my programming knowledge is still limited. If I make any progress, I will definitely let you know.

**Comment by Theggv** [comment]
Hi, add following lines to the `map_manager_nominations.sma`.
```diff
public clcmd_say(id)
{
    new text[MAPNAME_LENGTH]; read_args(text, charsmax(text));
    remove_quotes(text); trim(text); strtolower(text);

+    new prefix[32];
+    strtok2(text, prefix, charsmax(prefix), text, charsmax(text));
+    if(!equal(prefix, "nom") && !equal(prefix, "/nom")) return PLUGIN_CONTINUE;
    
    if(is_string_with_space(text)) return PLUGIN_CONTINUE;
    
    ...
}
```

**Comment by francisSM** [comment]
Hi Theggv,

Thank you very much for your prompt response and for providing a solution to my request. I have tested the modification and it worked perfectly.

I really appreciate your time and effort. Have a great day!
