### ISSUE TITLE
Question about SQL top15 database

### ISSUE THREAD

**Issue by gedaskofficial** [Theggv/Kreedz#39]
Hi there!

I would like to ask for some guidance. I am trying to make a website based on the sql records that are generated by the server, but the column 'time' in kz_records has a timestamp by the looks of it. I am just assuming thats the time the person finished the map.

My questions is, how would I convert it into a readable time? for example: 00:44.5?
When converting that timestamp it just gives me the date wayyy back.

I would greatly appreciate some guidance, thank you!

**Comment by Theggv** [comment]
Hi, time stored as packed float.

To convert it back to float you can use this:
https://github.com/Theggv/kreedz-top-backend/blob/master/src/records/utils/convertHexToFloat.ts

**Comment by gedaskofficial** [comment]
Thanks!

Sorry for my lack of knowledge, but timestamp I have is for example '1113254570' and this doesnt look like a hex value. I should get something like 00:02:04.45, do I need to somehow convert float to time after?

**Comment by Psycrow101** [comment]
Use convertHexToFloat function to get float seconds. After that, format the output like this:
```php
sprintf('%02d:%02d:%02d.%02d', ($seconds / 3600), ($seconds / 60 % 60), ($seconds % 60), ($seconds * 1000 % 1000 / 10));
```

**Comment by gedaskofficial** [comment]
Everything is working perfect, I really appreciate you guys helping me out even though this is and issue section, not some help section.
Thanks a lot!
