### ISSUE TITLE
Table "kz_records" is not created

### ISSUE THREAD

**Issue by hedqi** [Theggv/Kreedz#54]
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'STORED,
    INDEX user_idx (`user_id`),
    INDEX map_idx (`map_id`),
    INDEX rec_id' at line 11

![chrome_ZhEeuZO0Yk](https://github.com/Theggv/Kreedz/assets/118886387/1d498639-0817-4ad9-b296-f819636c49da)

**Comment by Flummi** [comment]
Just a quick note: MariaDB 5.5.68 is end-of-life and should no longer be used.
[Release Notes](https://mariadb.com/kb/en/mariadb-5568-release-notes/)
